.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "INTERNSCTL" "1" "December 2023" ""
.SH "NAME"
internsctl \- Custom Linux command for operations
.SH "SYNOPSIS"
\fBinternsctl\fR [OPTIONS] [ARGUMENTS]
.SH "DESCRIPTION"
\fBinternsctl\fR is a custom Linux command designed for specific operations\.
.SH "OPTIONS"
.IP "\[ci]" 4
\fB\-\-help\fR: Display this help message\.
.IP "\[ci]" 4
\fB\-\-version\fR: Display command version\.
.IP "\[ci]" 4
\fBcpu getinfo\fR: Display CPU information\.
.IP "\[ci]" 4
\fBmemory getinfo\fR: Display memory information\.
.IP "\[ci]" 4
\fBuser create <username>\fR: Create a new user\.
.IP "\[ci]" 4
\fBuser list [\-\-sudo\-only]\fR: List all users or users with sudo permissions\.
.IP "\[ci]" 4
\fBfile getinfo [OPTIONS] <file\-name>\fR: Get information about a file\.
.IP "" 0
.SH "EXAMPLES"
.IP "\[ci]" 4
\fBinternsctl \-\-help\fR
.IP "\[ci]" 4
\fBinternsctl \-\-version\fR
.IP "\[ci]" 4
\fBinternsctl cpu getinfo\fR
.IP "\[ci]" 4
\fBinternsctl memory getinfo\fR
.IP "\[ci]" 4
\fBinternsctl user create john_doe\fR
.IP "\[ci]" 4
\fBinternsctl user list\fR
.IP "\[ci]" 4
\fBinternsctl user list \-\-sudo\-only\fR
.IP "\[ci]" 4
\fBinternsctl file getinfo \-\-size hello\.txt\fR
.IP "\[ci]" 4
\fBinternsctl file getinfo \-\-permissions hello\.txt\fR
.IP "\[ci]" 4
\fBinternsctl file getinfo \-\-owner hello\.txt\fR
.IP "\[ci]" 4
\fBinternsctl file getinfo \-\-last\-modified hello\.txt\fR
.IP "" 0
.SH "AUTHOR"
Your Name
.SH "COPYRIGHT"
This is free software; see the source for copying conditions\. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\.
.SH "VERSION"
v0\.1\.0
